### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by schoeberl** [tjarker/framework#3]
```
make -C gcd         
make: *** gcd: No such file or directory.  Stop.
```

```
sbt "runMain GcdSim"
...
[error] -- [E008] Not Found Error: /Users/martin/source/tjarker/framework/src/main/scala/playground/Channel.scala:47:47 
```

**Comment by tjarker** [comment]
The make command failed, because I hadn't updated the documentation yet. The building of the verilator model is now taken care of from within scala, as it should be. 

The second error is related to that I am using virtual threads, which first were introduced in JDK19. I assume you are still in JDK17?

**Comment by schoeberl** [comment]
Yes, I am, but I think I could switch soon (maybe 21). Virtual threads sounds great. Is this coroutines?
